services:
  postgres_test:
    image: postgres:15-alpine
    container_name: bookmarks_test_db
    environment:
      POSTGRES_DB: bookmarks_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
