openapi: 3.0.3
info:
  title: Bookmarks API
  description: A RESTful API for managing website bookmarks with automatic metadata scraping
  version: 1.0.0

servers:
  - url: http://localhost:8081/api
    description: Local development server

paths:
  /bookmarks:
    post:
      summary: Create a new bookmark
      description: Creates a new bookmark and automatically fetches metadata from the URL
      operationId: createBookmark
      tags:
        - bookmarks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookmarkRequest'
      responses:
        '200':
          description: Bookmark created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookmarkResponse'
        '400':
          description: Invalid request body or URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    
    get:
      summary: List all bookmarks
      description: Retrieves a list of all bookmarks
      operationId: listBookmarks
      tags:
        - bookmarks
      responses:
        '200':
          description: List of bookmarks retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookmarksResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /bookmarks/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: ID of the bookmark
        schema:
          type: integer
          format: int64
    
    get:
      summary: Get a specific bookmark
      description: Retrieves a specific bookmark by ID
      operationId: getBookmark
      tags:
        - bookmarks
      responses:
        '200':
          description: Bookmark retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookmarkResponse'
        '404':
          description: Bookmark not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    
    delete:
      summary: Delete a bookmark
      description: Deletes a specific bookmark by ID
      operationId: deleteBookmark
      tags:
        - bookmarks
      responses:
        '200':
          description: Bookmark deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
        '404':
          description: Bookmark not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Bookmark:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        url:
          type: string
          format: uri
        title:
          type: string
        description:
          type: string
        favicon_url:
          type: string
          format: uri
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
        - url

    CreateBookmarkRequest:
      type: object
      properties:
        url:
          type: string
          format: uri
      required:
        - url

    BookmarkResponse:
      type: object
      properties:
        bookmark:
          $ref: '#/components/schemas/Bookmark'
        error:
          type: string

    BookmarksResponse:
      type: object
      properties:
        bookmarks:
          type: array
          items:
            $ref: '#/components/schemas/Bookmark'
        error:
          type: string

    DeleteResponse:
      type: object
      properties:
        success:
          type: boolean
        error:
          type: string
      required:
        - success

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
      required:
        - error

tags:
  - name: bookmarks
    description: Operations about bookmarks